spring:
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 10

  datasource:
    url: jdbc:h2:tcp://localhost/~/genie
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
